In [1]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import string

df = pd.read_excel("sentiment analysis.xlsx")

df

                                                   text  label
0                               "It's a waste of time."      0
1         "Everything turned out better than expected."      1
2                        "I learned so much from this."      1
3                       "That compliment made my week."      1
4                      "This is exactly what I needed."      1
...                                                 ...    ...
1095               I enjoyed every moment of the phone.      1
1096                   I absolutely loved the delivery.      1
1097  The restaurant was fantastic and exceeded my e...      1
1098  Iâ€™m extremely dissatisfied with the training...      0
1099                       This software ruined my day.      0

[1100 rows x 2 columns]

In [2]:
stop_words = stopwords.words("english")
ps = PorterStemmer()

In [3]:
def preprocessing(text):
    text = text.lower()
    token = nltk.word_tokenize(text)
    new = []
    for i in token:
        if i not in stop_words and i not in string.punctuation:
            stemmer = ps.stem(i)
            new.append(stemmer)
    return " ".join(new)

In [4]:
df["clean"] = df["text"].apply(preprocessing)

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

In [6]:
vector = TfidfVectorizer()
X = vector.fit_transform(df["clean"])
y = df["label"]

In [7]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,
                                                random_state=55)

In [8]:
log = LogisticRegression()
log.fit(X_train,y_train)
print("LogisticRegression()")
print("train accuracy",log.score(X_train,y_train))
print("test accuracy",log.score(X_test,y_test))

LogisticRegression()
train accuracy 0.9961038961038962
test accuracy 0.9575757575757575

In [9]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(random_state=88)

In [10]:
dt.fit(X_train,y_train)
print("train accuracy",dt.score(X_train,y_train))
print("test accuracy",dt.score(X_test,y_test))

train accuracy 1.0
test accuracy 0.9515151515151515

In [11]:
from sklearn.metrics import classification_report

In [12]:
print(classification_report(y_train,log.predict(X_train)))
print(classification_report(y_test,log.predict(X_test)))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00       386
           1       0.99      1.00      1.00       384

    accuracy                           1.00       770
   macro avg       1.00      1.00      1.00       770
weighted avg       1.00      1.00      1.00       770

              precision    recall  f1-score   support

           0       0.93      0.99      0.96       164
           1       0.99      0.92      0.96       166

    accuracy                           0.96       330
   macro avg       0.96      0.96      0.96       330
weighted avg       0.96      0.96      0.96       330

In [13]:
def pred_text(text):
    text = text.lower()
    text = preprocessing(text)
    vec = vector.transform([text])
    predict = dt.predict(vec)[0]
    if predict == 1:
        return "positive 😊"
    else:
        return "negative 😔"

In [15]:
print(pred_text("i hate you"))

positive 😊

In [30]:
df[["text","label"]].sample(5)

                                                  text  label
182          Iâ€™m extremely satisfied with the hotel.      1
748                    I absolutely hated the service.      0
422                      I absolutely hated the hotel.      0
116  The book works perfectly and I highly recommen...      1
727          Iâ€™m extremely satisfied with the movie.      1