In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [1]:
import numpy as np
import pandas as pd
import keras
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import keras.models as km
from keras.models import Sequential
from keras import activations, initializers, regularizers, constraints
from keras.layers import Dense, Activation

ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "C:\Users\sarth\anaconda3\python.exe"
  * The NumPy version is: "1.21.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.

ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "C:\Users\sarth\anaconda3\python.exe"
  * The NumPy version is: "1.21.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.

ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "C:\Users\sarth\anaconda3\python.exe"
  * The NumPy version is: "1.21.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.

ImportError: _multiarray_umath failed to import

ImportError: numpy._core.umath failed to import

In [3]:
dataset=pd.read_csv("Churn_Modelling.csv")

In [4]:
dataset.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [5]:
dataset.tail()

      RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[5 rows x 14 columns]

In [6]:
dataset.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, inplace=True)

In [7]:
dataset_new = pd.get_dummies(dataset, ['Geography', 'Gender'], drop_first=True)
dataset_new.head()

   CreditScore  Age  Tenure  ...  Geography_Germany  Geography_Spain  Gender_Male
0          619   42       2  ...                  0                0            0
1          608   41       1  ...                  0                1            0
2          502   42       8  ...                  0                0            0
3          699   39       1  ...                  0                0            0
4          850   43       2  ...                  0                1            0

[5 rows x 12 columns]

In [8]:
X = dataset_new.drop(columns=["Exited"])
y = dataset_new['Exited']

In [9]:
dataset["Exited"].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [10]:
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.3, random_state =123)

In [11]:
train_X.shape[1]

11

In [12]:
sc = StandardScaler()
train_X = sc.fit_transform(train_X)
test_X = sc.transform(test_X)

In [13]:
model = Sequential()
model.add(Dense(units = 11, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
model.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
model.add(Dense(units = 4, kernel_initializer = 'uniform', activation = 'relu'))
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 11)                132

 dense_1 (Dense)             (None, 6)                 72

 dense_2 (Dense)             (None, 4)                 28

 dense_3 (Dense)             (None, 1)                 5

=================================================================
Total params: 237
Trainable params: 237
Non-trainable params: 0
_________________________________________________________________

In [21]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_5 (Dense)             (None, 10)                120

 dense_6 (Dense)             (None, 8)                 88

 dense_7 (Dense)             (None, 2)                 18

 dense_8 (Dense)             (None, 1)                 3

=================================================================
Total params: 229
Trainable params: 229
Non-trainable params: 0
_________________________________________________________________

In [15]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [16]:
train_X.shape

(7000, 11)

In [17]:
model.fit(train_X, train_y, batch_size = 10, epochs = 10)

Epoch 1/10
700/700 [==============================] - 2s 2ms/step - loss: 0.4943 - accuracy: 0.7950
Epoch 2/10
700/700 [==============================] - 1s 2ms/step - loss: 0.4333 - accuracy: 0.7954
Epoch 3/10
700/700 [==============================] - 1s 2ms/step - loss: 0.4281 - accuracy: 0.7954
Epoch 4/10
700/700 [==============================] - 1s 2ms/step - loss: 0.4236 - accuracy: 0.7991
Epoch 5/10
700/700 [==============================] - 1s 2ms/step - loss: 0.4203 - accuracy: 0.8223
Epoch 6/10
700/700 [==============================] - 1s 2ms/step - loss: 0.4180 - accuracy: 0.8246
Epoch 7/10
700/700 [==============================] - 1s 2ms/step - loss: 0.4170 - accuracy: 0.8274
Epoch 8/10
700/700 [==============================] - 1s 2ms/step - loss: 0.4151 - accuracy: 0.8283
Epoch 9/10
700/700 [==============================] - 1s 2ms/step - loss: 0.4144 - accuracy: 0.8300
Epoch 10/10
700/700 [==============================] - 1s 2ms/step - loss: 0.4127 - accuracy: 0.8310

In [18]:
prob_test=model.predict(test_X)  # Probability 
prob_test

array([[0.07163593],
       [0.03792268],
       [0.01677439],
       ...,
       [0.08754399],
       [0.11823046],
       [0.02671042]], dtype=float32)

In [19]:
from sklearn import metrics
y_test_pred=np.where(prob_test>0.5,1,0)
print(metrics.classification_report(test_y, y_test_pred))

              precision    recall  f1-score   support

           0       0.83      0.99      0.90      2395
           1       0.80      0.22      0.35       605

    accuracy                           0.83      3000
   macro avg       0.82      0.60      0.63      3000
weighted avg       0.83      0.83      0.79      3000